name: Build and Save Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t glaxs .

      - name: Archive Image
        run: docker save -o docker1.tar glaxs

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker1-image
          path: docker1.tar
